<?php

declare(strict_types=1);

return [
    'FlatType' => [
        'description' => 'Тип помещения',
        'partitionsCount' => 1,
        'xmlPath' => '/FlatTypes/FlatType',
        'insertFileMask' => 'AS_FLATTYPE_*.XML',
        'deleteFileMask' => 'AS_DEL_FLATTYPE_*.XML',
        'fields' => [
            'FLTYPEID' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => true,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Тип помещения',
            ],
            'NAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 20,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Наименование',
            ],
            'SHORTNAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 20,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Краткое наименование',
            ],
        ],
    ],
    'ActualStatus' => [
        'description' => 'Статус актуальности ФИАС',
        'partitionsCount' => 1,
        'xmlPath' => '/ActualStatuses/ActualStatus',
        'insertFileMask' => 'AS_ACTSTAT_*.XML',
        'deleteFileMask' => 'AS_DEL_ACTSTAT_*.XML',
        'fields' => [
            'ACTSTATID' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => true,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Идентификатор статуса (ключ)',
            ],
            'NAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 100,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Наименование
0 – Не актуальный
1 – Актуальный (последняя запись по адресному объекту)
',
            ],
        ],
    ],
    'OperationStatus' => [
        'description' => 'Статус действия',
        'partitionsCount' => 1,
        'xmlPath' => '/OperationStatuses/OperationStatus',
        'insertFileMask' => 'AS_OPERSTAT_*.XML',
        'deleteFileMask' => 'AS_DEL_OPERSTAT_*.XML',
        'fields' => [
            'OPERSTATID' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => true,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Идентификатор статуса (ключ)',
            ],
            'NAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 100,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Наименование
01 – Инициация;
10 – Добавление;
20 – Изменение;
21 – Групповое изменение;
30 – Удаление;
31 - Удаление вследствие удаления вышестоящего объекта;
40 – Присоединение адресного объекта (слияние);
41 – Переподчинение вследствие слияния вышестоящего объекта;
42 - Прекращение существования вследствие присоединения к другому адресному объекту;
43 - Создание нового адресного объекта в результате слияния адресных объектов;
50 – Переподчинение;
51 – Переподчинение вследствие переподчинения вышестоящего объекта;
60 – Прекращение существования вследствие дробления;
61 – Создание нового адресного объекта в результате дробления;
70 – Восстановление объекта прекратившего существование',
            ],
        ],
    ],
    'Room' => [
        'description' => 'Классификатор помещениях',
        'partitionsCount' => 4,
        'xmlPath' => '/Rooms/Room',
        'insertFileMask' => 'AS_ROOM_*.XML',
        'deleteFileMask' => 'AS_DEL_ROOM_*.XML',
        'fields' => [
            'ROOMID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => false,
                'isPrimary' => true,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Уникальный идентификатор записи. Ключевое поле.',
                'length' => 36,
            ],
            'ROOMGUID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Глобальный уникальный идентификатор адресного объекта (помещения)',
                'length' => 36,
            ],
            'HOUSEGUID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Идентификатор родительского объекта (дома)',
                'length' => 36,
            ],
            'REGIONCODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 2,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код региона',
            ],
            'FLATNUMBER' => [
                'type' => 'string',
                'subType' => '',
                'length' => 50,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Номер помещения или офиса',
            ],
            'FLATTYPE' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Тип помещения',
            ],
            'POSTALCODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 6,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Почтовый индекс',
            ],
            'STARTDATE' => [
                'type' => 'string',
                'subType' => 'date',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Начало действия записи',
            ],
            'ENDDATE' => [
                'type' => 'string',
                'subType' => 'date',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Окончание действия записи',
            ],
            'UPDATEDATE' => [
                'type' => 'string',
                'subType' => 'date',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Дата  внесения записи',
            ],
            'OPERSTATUS' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Статус действия над записью – причина появления записи (см. описание таблицы OperationStatus):
01 – Инициация;
10 – Добавление;
20 – Изменение;
21 – Групповое изменение;
30 – Удаление;
31 - Удаление вследствие удаления вышестоящего объекта;
40 – Присоединение адресного объекта (слияние);
41 – Переподчинение вследствие слияния вышестоящего объекта;
42 - Прекращение существования вследствие присоединения к другому адресному объекту;
43 - Создание нового адресного объекта в результате слияния адресных объектов;
50 – Переподчинение;
51 – Переподчинение вследствие переподчинения вышестоящего объекта;
60 – Прекращение существования вследствие дробления;
61 – Создание нового адресного объекта в результате дробления
',
            ],
            'LIVESTATUS' => [
                'type' => 'int',
                'subType' => '',
                'length' => 255,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Признак действующего адресного объекта',
            ],
            'NORMDOC' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Внешний ключ на нормативный документ',
                'length' => 36,
            ],
            'ROOMNUMBER' => [
                'type' => 'string',
                'subType' => '',
                'isNullable' => true,
                'description' => 'Номер комнаты',
                'length' => 50,
            ],
            'ROOMTYPE' => [
                'type' => 'int',
                'subType' => '',
                'isNullable' => true,
                'description' => 'Тип комнаты',
            ],
            'PREVID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => true,
                'description' => 'Идентификатор записи связывания с предыдушей исторической записью',
                'length' => 36,
            ],
            'NEXTID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => true,
                'description' => 'Идентификатор записи  связывания с последующей исторической записью',
                'length' => 36,
            ],
            'CADNUM' => [
                'type' => 'string',
                'subType' => '',
                'isNullable' => true,
                'description' => 'Кадастровый номер помещения',
                'length' => 100,
            ],
            'ROOMCADNUM' => [
                'type' => 'string',
                'subType' => '',
                'isNullable' => true,
                'description' => 'Кадастровый номер комнаты в помещении',
                'length' => 100,
            ],
        ],
    ],
    'AddressObjectType' => [
        'description' => 'Тип адресного объекта',
        'partitionsCount' => 1,
        'xmlPath' => '/AddressObjectTypes/AddressObjectType',
        'insertFileMask' => 'AS_SOCRBASE_*.XML',
        'deleteFileMask' => 'AS_DEL_SOCRBASE_*.XML',
        'fields' => [
            'KOD_T_ST' => [
                'type' => 'string',
                'subType' => '',
                'length' => 4,
                'isNullable' => false,
                'isPrimary' => true,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Ключевое поле',
            ],
            'LEVEL' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Уровень адресного объекта',
            ],
            'SOCRNAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 50,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Полное наименование типа объекта',
            ],
            'SCNAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 10,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Краткое наименование типа объекта',
            ],
        ],
    ],
    'RoomType' => [
        'description' => 'Тип комнаты',
        'partitionsCount' => 1,
        'xmlPath' => '/RoomTypes/RoomType',
        'insertFileMask' => 'AS_ROOMTYPE_*.XML',
        'deleteFileMask' => 'AS_DEL_ROOMTYPE_*.XML',
        'fields' => [
            'RMTYPEID' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => true,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Тип комнаты',
            ],
            'NAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 20,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Наименование',
            ],
            'SHORTNAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 20,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Краткое наименование',
            ],
        ],
    ],
    'Stead' => [
        'description' => 'Классификатор земельных участков',
        'partitionsCount' => 1,
        'xmlPath' => '/Steads/Stead',
        'insertFileMask' => 'AS_STEAD_*.XML',
        'deleteFileMask' => 'AS_DEL_STEAD_*.XML',
        'fields' => [
            'STEADGUID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Глобальный уникальный идентификатор адресного объекта (земельного участка)',
                'length' => 36,
            ],
            'NUMBER' => [
                'type' => 'string',
                'subType' => '',
                'length' => 120,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Номер земельного участка',
            ],
            'REGIONCODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 2,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код региона',
            ],
            'POSTALCODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 6,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Почтовый индекс',
            ],
            'IFNSFL' => [
                'type' => 'string',
                'subType' => '',
                'length' => 4,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код ИФНС ФЛ',
            ],
            'IFNSUL' => [
                'type' => 'string',
                'subType' => '',
                'length' => 4,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код ИФНС ЮЛ',
            ],
            'OKATO' => [
                'type' => 'string',
                'subType' => '',
                'length' => 11,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'OKATO',
            ],
            'OKTMO' => [
                'type' => 'string',
                'subType' => '',
                'length' => 11,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'OKTMO',
            ],
            'PARENTGUID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Идентификатор объекта родительского объекта',
                'length' => 36,
            ],
            'STEADID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => false,
                'isPrimary' => true,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Уникальный идентификатор записи. Ключевое поле.',
                'length' => 36,
            ],
            'OPERSTATUS' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Статус действия над записью – причина появления записи (см. описание таблицы OperationStatus):
01 – Инициация;
10 – Добавление;
20 – Изменение;
21 – Групповое изменение;
30 – Удаление;
31 - Удаление вследствие удаления вышестоящего объекта;
40 – Присоединение адресного объекта (слияние);
41 – Переподчинение вследствие слияния вышестоящего объекта;
42 - Прекращение существования вследствие присоединения к другому адресному объекту;
43 - Создание нового адресного объекта в результате слияния адресных объектов;
50 – Переподчинение;
51 – Переподчинение вследствие переподчинения вышестоящего объекта;
60 – Прекращение существования вследствие дробления;
61 – Создание нового адресного объекта в результате дробления
',
            ],
            'STARTDATE' => [
                'type' => 'string',
                'subType' => 'date',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Начало действия записи',
            ],
            'ENDDATE' => [
                'type' => 'string',
                'subType' => 'date',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Окончание действия записи',
            ],
            'UPDATEDATE' => [
                'type' => 'string',
                'subType' => 'date',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Дата  внесения записи',
            ],
            'LIVESTATUS' => [
                'type' => 'int',
                'subType' => '',
                'length' => 255,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Признак действующего адресного объекта',
            ],
            'DIVTYPE' => [
                'type' => 'int',
                'subType' => '',
                'length' => 255,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Тип адресации:
0 - не определено
1 - муниципальный;
2 - административно-территориальный',
            ],
            'NORMDOC' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Внешний ключ на нормативный документ',
                'length' => 36,
            ],
            'TERRIFNSFL' => [
                'type' => 'string',
                'subType' => '',
                'isNullable' => true,
                'description' => 'Код территориального участка ИФНС ФЛ',
                'length' => 4,
            ],
            'TERRIFNSUL' => [
                'type' => 'string',
                'subType' => '',
                'isNullable' => true,
                'description' => 'Код территориального участка ИФНС ЮЛ',
                'length' => 4,
            ],
            'PREVID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => true,
                'description' => 'Идентификатор записи связывания с предыдушей исторической записью',
                'length' => 36,
            ],
            'NEXTID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => true,
                'description' => 'Идентификатор записи  связывания с последующей исторической записью',
                'length' => 36,
            ],
            'CADNUM' => [
                'type' => 'string',
                'subType' => '',
                'isNullable' => true,
                'description' => 'Кадастровый номер',
                'length' => 100,
            ],
        ],
    ],
    'CenterStatus' => [
        'description' => 'Статус центра',
        'partitionsCount' => 1,
        'xmlPath' => '/CenterStatuses/CenterStatus',
        'insertFileMask' => 'AS_CENTERST_*.XML',
        'deleteFileMask' => 'AS_DEL_CENTERST_*.XML',
        'fields' => [
            'CENTERSTID' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => true,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Идентификатор статуса',
            ],
            'NAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 100,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Наименование',
            ],
        ],
    ],
    'NormativeDocument' => [
        'description' => 'Сведения по нормативному документу, являющемуся основанием присвоения адресному элементу наименования',
        'partitionsCount' => 1,
        'xmlPath' => '/NormativeDocumentes/NormativeDocument',
        'insertFileMask' => 'AS_NORMDOC_*.XML',
        'deleteFileMask' => 'AS_DEL_NORMDOC_*.XML',
        'fields' => [
            'NORMDOCID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => false,
                'isPrimary' => true,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Идентификатор нормативного документа',
                'length' => 36,
            ],
            'DOCNAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 1000,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Наименование документа',
            ],
            'DOCDATE' => [
                'type' => 'string',
                'subType' => 'date',
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Дата документа',
            ],
            'DOCNUM' => [
                'type' => 'string',
                'subType' => '',
                'length' => 250,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Номер документа',
            ],
            'DOCTYPE' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Тип документа',
            ],
            'DOCIMGID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => true,
                'description' => 'Идентификатор образа (внешний ключ)',
                'length' => 36,
            ],
        ],
    ],
    'CurrentStatus' => [
        'description' => 'Статус актуальности КЛАДР 4.0',
        'partitionsCount' => 1,
        'xmlPath' => '/CurrentStatuses/CurrentStatus',
        'insertFileMask' => 'AS_CURENTST_*.XML',
        'deleteFileMask' => 'AS_DEL_CURENTST_*.XML',
        'fields' => [
            'CURENTSTID' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => true,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Идентификатор статуса (ключ)',
            ],
            'NAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 100,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Наименование (0 - актуальный, 1-50, 2-98 – исторический (кроме 51), 51 - переподчиненный, 99 - несуществующий)',
            ],
        ],
    ],
    'NormativeDocumentType' => [
        'description' => 'Тип нормативного документа',
        'partitionsCount' => 1,
        'xmlPath' => '/NormativeDocumentTypes/NormativeDocumentType',
        'insertFileMask' => 'AS_NDOCTYPE_*.XML',
        'deleteFileMask' => 'AS_DEL_NDOCTYPE_*.XML',
        'fields' => [
            'NDTYPEID' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => true,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Идентификатор записи (ключ)',
            ],
            'NAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 250,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Наименование типа нормативного документа',
            ],
        ],
    ],
    'EstateStatus' => [
        'description' => 'Признак владения',
        'partitionsCount' => 1,
        'xmlPath' => '/EstateStatuses/EstateStatus',
        'insertFileMask' => 'AS_ESTSTAT_*.XML',
        'deleteFileMask' => 'AS_DEL_ESTSTAT_*.XML',
        'fields' => [
            'ESTSTATID' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => true,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Признак владения',
            ],
            'NAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 20,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Наименование',
            ],
            'SHORTNAME' => [
                'type' => 'string',
                'subType' => '',
                'isNullable' => true,
                'description' => 'Краткое наименование',
                'length' => 20,
            ],
        ],
    ],
    'AddressObject' => [
        'description' => 'Классификатор адресообразующих элементов',
        'partitionsCount' => 1,
        'xmlPath' => '/AddressObjects/Object',
        'insertFileMask' => 'AS_ADDROBJ_*.XML',
        'deleteFileMask' => 'AS_DEL_ADDROBJ_*.XML',
        'fields' => [
            'AOID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => false,
                'isPrimary' => true,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Уникальный идентификатор записи. Ключевое поле.',
                'length' => 36,
            ],
            'AOGUID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => true,
                'isPartition' => false,
                'description' => 'Глобальный уникальный идентификатор адресного объекта ',
                'length' => 36,
            ],
            'PARENTGUID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Идентификатор объекта родительского объекта',
                'length' => 36,
            ],
            'PREVID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Идентификатор записи связывания с предыдушей исторической записью',
                'length' => 36,
            ],
            'NEXTID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Идентификатор записи  связывания с последующей исторической записью',
                'length' => 36,
            ],
            'CODE' => [
                'type' => 'string',
                'subType' => '',
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код адресного объекта одной строкой с признаком актуальности из КЛАДР 4.0. ',
                'length' => 17,
            ],
            'FORMALNAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 120,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Формализованное наименование',
            ],
            'OFFNAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 120,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Официальное наименование',
            ],
            'SHORTNAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Краткое наименование типа объекта',
            ],
            'AOLEVEL' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Уровень адресного объекта ',
            ],
            'REGIONCODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 2,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код региона',
            ],
            'AREACODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 3,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код района',
            ],
            'AUTOCODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 1,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код автономии',
            ],
            'CITYCODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 3,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код города',
            ],
            'CTARCODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 3,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код внутригородского района',
            ],
            'PLACECODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 3,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код населенного пункта',
            ],
            'PLANCODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 4,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код элемента планировочной структуры',
            ],
            'STREETCODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 4,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код улицы',
            ],
            'EXTRCODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 4,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код дополнительного адресообразующего элемента',
            ],
            'SEXTCODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 3,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код подчиненного дополнительного адресообразующего элемента',
            ],
            'PLAINCODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 15,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код адресного объекта из КЛАДР 4.0 одной строкой без признака актуальности (последних двух цифр)',
            ],
            'CURRSTATUS' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Статус актуальности КЛАДР 4 (последние две цифры в коде)',
            ],
            'ACTSTATUS' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Статус актуальности адресного объекта ФИАС. Актуальный адрес на текущую дату. Обычно последняя запись об адресном объекте.
0 – Не актуальный
1 - Актуальный
',
            ],
            'LIVESTATUS' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Признак действующего адресного объекта',
            ],
            'CENTSTATUS' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Статус центра',
            ],
            'OPERSTATUS' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Статус действия над записью – причина появления записи (см. описание таблицы OperationStatus):
01 – Инициация;
10 – Добавление;
20 – Изменение;
21 – Групповое изменение;
30 – Удаление;
31 - Удаление вследствие удаления вышестоящего объекта;
40 – Присоединение адресного объекта (слияние);
41 – Переподчинение вследствие слияния вышестоящего объекта;
42 - Прекращение существования вследствие присоединения к другому адресному объекту;
43 - Создание нового адресного объекта в результате слияния адресных объектов;
50 – Переподчинение;
51 – Переподчинение вследствие переподчинения вышестоящего объекта;
60 – Прекращение существования вследствие дробления;
61 – Создание нового адресного объекта в результате дробления
',
            ],
            'IFNSFL' => [
                'type' => 'string',
                'subType' => '',
                'length' => 4,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код ИФНС ФЛ',
            ],
            'IFNSUL' => [
                'type' => 'string',
                'subType' => '',
                'length' => 4,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код ИФНС ЮЛ',
            ],
            'TERRIFNSFL' => [
                'type' => 'string',
                'subType' => '',
                'length' => 4,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код территориального участка ИФНС ФЛ',
            ],
            'TERRIFNSUL' => [
                'type' => 'string',
                'subType' => '',
                'length' => 4,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код территориального участка ИФНС ЮЛ',
            ],
            'OKATO' => [
                'type' => 'string',
                'subType' => '',
                'length' => 11,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'OKATO',
            ],
            'OKTMO' => [
                'type' => 'string',
                'subType' => '',
                'length' => 11,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'OKTMO',
            ],
            'POSTALCODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 6,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Почтовый индекс',
            ],
            'STARTDATE' => [
                'type' => 'string',
                'subType' => 'date',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Начало действия записи',
            ],
            'ENDDATE' => [
                'type' => 'string',
                'subType' => 'date',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Окончание действия записи',
            ],
            'UPDATEDATE' => [
                'type' => 'string',
                'subType' => 'date',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Дата  внесения записи',
            ],
            'DIVTYPE' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => '
                  Тип адресации:
                  0 - не определено
                  1 - муниципальный;
                  2 - административно-территориальный
                ',
            ],
            'NORMDOC' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => true,
                'description' => 'Внешний ключ на нормативный документ',
                'length' => 36,
            ],
        ],
    ],
    'House' => [
        'description' => 'Сведения по номерам домов улиц городов и населенных пунктов',
        'partitionsCount' => 4,
        'xmlPath' => '/Houses/House',
        'insertFileMask' => 'AS_HOUSE_*.XML',
        'deleteFileMask' => 'AS_DEL_HOUSE_*.XML',
        'fields' => [
            'HOUSEID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => false,
                'isPrimary' => true,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Уникальный идентификатор записи дома',
                'length' => 36,
            ],
            'HOUSEGUID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Глобальный уникальный идентификатор дома',
                'length' => 36,
            ],
            'AOGUID' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Guid записи родительского объекта (улицы, города, населенного пункта и т.п.)',
                'length' => 36,
            ],
            'HOUSENUM' => [
                'type' => 'string',
                'subType' => '',
                'length' => 20,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Номер дома',
            ],
            'STRSTATUS' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Признак строения',
            ],
            'ESTSTATUS' => [
                'type' => 'int',
                'subType' => '',
                'length' => 2,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Признак владения',
            ],
            'STATSTATUS' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Состояние дома',
            ],
            'IFNSFL' => [
                'type' => 'string',
                'subType' => '',
                'length' => 4,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код ИФНС ФЛ',
            ],
            'IFNSUL' => [
                'type' => 'string',
                'subType' => '',
                'length' => 4,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Код ИФНС ЮЛ',
            ],
            'OKATO' => [
                'type' => 'string',
                'subType' => '',
                'length' => 11,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'OKATO',
            ],
            'OKTMO' => [
                'type' => 'string',
                'subType' => '',
                'length' => 11,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'OKTMO',
            ],
            'POSTALCODE' => [
                'type' => 'string',
                'subType' => '',
                'length' => 6,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Почтовый индекс',
            ],
            'STARTDATE' => [
                'type' => 'string',
                'subType' => 'date',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Начало действия записи',
            ],
            'ENDDATE' => [
                'type' => 'string',
                'subType' => 'date',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Окончание действия записи',
            ],
            'UPDATEDATE' => [
                'type' => 'string',
                'subType' => 'date',
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Дата время внесения записи',
            ],
            'COUNTER' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Счетчик записей домов для КЛАДР 4',
            ],
            'DIVTYPE' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Тип адресации:
0 - не определено
1 - муниципальный;
2 - административно-территориальный',
            ],
            'REGIONCODE' => [
                'type' => 'string',
                'subType' => '',
                'isNullable' => true,
                'description' => 'Код региона',
                'length' => 2,
            ],
            'TERRIFNSFL' => [
                'type' => 'string',
                'subType' => '',
                'isNullable' => true,
                'description' => 'Код территориального участка ИФНС ФЛ',
                'length' => 4,
            ],
            'TERRIFNSUL' => [
                'type' => 'string',
                'subType' => '',
                'isNullable' => true,
                'description' => 'Код территориального участка ИФНС ЮЛ',
                'length' => 4,
            ],
            'BUILDNUM' => [
                'type' => 'string',
                'subType' => '',
                'isNullable' => true,
                'description' => 'Номер корпуса',
                'length' => 50,
            ],
            'STRUCNUM' => [
                'type' => 'string',
                'subType' => '',
                'isNullable' => true,
                'description' => 'Номер строения',
                'length' => 50,
            ],
            'NORMDOC' => [
                'type' => 'string',
                'subType' => 'uuid',
                'isNullable' => true,
                'description' => 'Внешний ключ на нормативный документ',
                'length' => 36,
            ],
            'CADNUM' => [
                'type' => 'string',
                'subType' => '',
                'isNullable' => true,
                'description' => 'Кадастровый номер',
                'length' => 100,
            ],
        ],
    ],
    'StructureStatus' => [
        'description' => 'Признак строения',
        'partitionsCount' => 1,
        'xmlPath' => '/StructureStatuses/StructureStatus',
        'insertFileMask' => 'AS_STRSTAT_*.XML',
        'deleteFileMask' => 'AS_DEL_STRSTAT_*.XML',
        'fields' => [
            'STRSTATID' => [
                'type' => 'int',
                'subType' => '',
                'length' => 10,
                'isNullable' => false,
                'isPrimary' => true,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Признак строения',
            ],
            'NAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 20,
                'isNullable' => false,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Наименование',
            ],
            'SHORTNAME' => [
                'type' => 'string',
                'subType' => '',
                'length' => 20,
                'isNullable' => true,
                'isPrimary' => false,
                'isIndex' => false,
                'isPartition' => false,
                'description' => 'Краткое наименование',
            ],
        ],
    ],
];
